name: Build Extension
on:
  push:
    branches:
      - main
      - dev
    tags:
      - v*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd sidebar
          npm install

      - name: Build project
        run: |
          cd sidebar
          npm run build

      - name: Package Extension
        uses: cardinalby/webext-buildtools-pack-extension-dir-action@v1
        with:
          extensionDir: '.'
          zipFilePath: 'build/extension.zip'
          zipIgnore: '*.pem|.git|*.crx|.github|sidebar|_metadata|screenshot.png'
      
      - name: Sigheck Extension
        uses: cardinalby/webext-buildtools-chrome-crx-action@v2
        with:
          # zip file made at the packExtensionDir step
          zipFilePath: 'build/extension.zip'
          crxFilePath: 'build/extension.crx'
          privateKey: ${{ secrets.CHROME_CRX_PRIVATE_KEY }}

      - name: Upload Extension
        uses: actions/upload-artifact@v2
        with:
          name: extension
          path: build/extension.zip
      
      - name: Upload CRX
        uses: actions/upload-artifact@v2
        with:
          name: crx
          path: build/extension.crx

  release:
    needs: build
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Download Extension
        uses: actions/download-artifact@v2
        with:
          name: extension
          path: build

      - name: Download CRX
        uses: actions/download-artifact@v2
        with:
          name: crx
          path: build

      - name: Create Release and Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/extension.zip
            build/extension.crx